### PR TITLE
fix: remove keypad visibility if not enabled

### LINKED ISSUE #546: Design difference between figma and the release candidate
Image
Image

### PR DESCRIPTION
**Pull request by rhbrunetto**
## Changes

- Removes keypad visibility on `ODPConfirmationRoute` if not enabled;
- Fixes minor UI differences from Figma (see #546)

<details><summary>Keypad visibility removed</summary>

Simulator Screen Shot - iPhone 14 Pro Max - 2022-10-25 at 11 28 57

</details>

<details><summary>Figma UI comparison</summary>
Figma:

iPhone 14 Pro Max:

Simulator Screen Shot - iPhone 14 Pro Max - 2022-10-25 at 11 28 26

</details>

## Related issues

Fixes #546 

## Checklist

- [x] PR is ready for review (if not, it should be a draft).
- [x] PR title follows [Conventional Commits][1] guidelines.
- [x] Screenshots/video added.
- [ ] Tests added.
- [x] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

### CODE REVIEW

File: packages/cryptoplease/lib/app/components/usdc_info.dart [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+import 'package:cryptoplease/ui/info_icon.dart';
+import 'package:cryptoplease/ui/info_widget.dart';
+import 'package:flutter/material.dart';
+
+class UsdcInfoWidget extends StatelessWidget {
+  const UsdcInfoWidget({Key? key}) : super(key: key);
+
+  @override
+  Widget build(BuildContext context) {
+    final screenHeight = MediaQuery.of(context).size.height;
```
Comment (ookami-kb) [inline packages/cryptoplease/lib/app/components/usdc_info.dart:11]: This was true for the specific screen, if you're making this widget reusable, it should rather use `LayoutBuilder` and calculate the sizes based on the available layout constraints, not on the screen size.

**Review by ookami-kb — CHANGES_REQUESTED** [review]

**Review by ookami-kb — APPROVED** [review]
