### PR TITLE
fix: add padding at the bottom of 'Select Token' list

### LINKED ISSUE #389: No padding at the bottom of "Select token" list
**Describe the bug**

**To Reproduce**

1. Go to Swap page
2. Click on source token selector
3. Scroll down to the bottom

**Expected behavior**

Add padding.

**Screenshots**

**Smartphone:**
 - Device: iPhone13
 - OS: iOS15.2
 - master branch

### PR DESCRIPTION
**Pull request by moksh-mahajan**
## Changes

Wrapped SliverList widget in the `TokenList` with SliverPadding and provided it a bottom padding value of 64.

## Related issues

Fixes #389 

### Screenshot
photo_6075849260672332232_y

## Checklist

- [x] PR is ready for review (if not, it should be a draft).
- [x] PR title follows [Conventional Commits][1] guidelines.
- [x] Screenshots/video added.
- [ ] Tests added.
- [x] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

### CODE REVIEW

File: packages/cryptoplease/lib/core/presentation/token_selector_screen.dart [hunk 1]
```diff
@@ -148,20 +148,23 @@ class _TokenList extends StatelessWidget {
...
-              token: token,
-              onSelect: onTokenSelected,
-              balance: shouldDisplayAmount
-                  ? context.watchUserCryptoBalance(token)
-                  : null,
-            );
-          },
-          childCount: tokens.length,
+  Widget build(BuildContext context) => SliverPadding(
+        padding: const EdgeInsets.only(bottom: 64),
```
Comment (ookami-kb) [inline packages/cryptoplease/lib/core/presentation/token_selector_screen.dart:152]: Let's rather use `cpNavigationBarheight` instead.

**Review by ookami-kb — CHANGES_REQUESTED** [review]

**Review by ookami-kb — APPROVED** [review]
