### PR TITLE
fix: use env for solana rpc url on solana pay

### LINKED ISSUE #726: bug payment with phantom is not working anymore
phantom

### PR DESCRIPTION
**Pull request by rhbrunetto**
## Changes

- Sets Solana RPC url via environment variable

## Related issues

Fixes #726 

## Checklist

- [x] PR is ready for review (if not, it should be a draft).
- [x] PR title follows [Conventional Commits][1] guidelines.
- [ ] Screenshots/video added.
- [ ] Tests added.
- [x] Self-review done.

[1]: https://www.conventionalcommits.org/en/v1.0.0/

### CODE REVIEW

File: packages/cryptoplease_link/public/scripts/phantom-app.js [hunk 1]
```diff
@@ -46,9 +57,9 @@ const _createAndSendTransaction = async function (publicKey, recipient) {
     const provider = window.solana;
     await provider.signAndSendTransaction(transaction);
 
-    alert('Payment has been sent successfully!');
+    alert("Payment has been sent successfully!");
   } catch (err) {
     console.warn(err);
-    alert('Error sending the transaction!');
+    alert("Error sending the transaction!");
```
Comment (ookami-kb) [inline packages/cryptoplease_link/public/scripts/phantom-app.js:63]: Please remove these non-meaningful changes like quotes.

**Review by ookami-kb — APPROVED** [review]
